/// <reference types="node" />

/**
 * Writes dist/tailwind/preset.js, dist/tailwind/theme.css,
 * and src/tokens/generated/tailwind-theme.css from gkTokens.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  buildGodKitTailwindExtend,
  buildGodKitTailwindThemeCss,
} from '../src/tokens/tailwind-theme-build'

const root = fileURLToPath(new URL('..', import.meta.url))
const distTailwind = join(root, 'dist', 'tailwind')
const generatedDir = join(root, 'src', 'tokens', 'generated')

const banner =
  '/**\n * Generated by scripts/generate-tailwind-artifacts.ts — do not edit.\n */\n\n'

function presetModule(): string {
  const extend = buildGodKitTailwindExtend()
  return `${banner}export default {\n  theme: {\n    extend: ${JSON.stringify(extend, null, 2)},\n  },\n}\n`
}

mkdirSync(distTailwind, { recursive: true })
mkdirSync(generatedDir, { recursive: true })

const themeCss = buildGodKitTailwindThemeCss()

writeFileSync(join(distTailwind, 'preset.js'), presetModule(), 'utf8')
writeFileSync(join(distTailwind, 'theme.css'), themeCss, 'utf8')
writeFileSync(join(generatedDir, 'tailwind-theme.css'), themeCss, 'utf8')
