/**
 * Typed token names for CSS variables (use with getComputedStyle or documentation).
 */
export const gkTokens = {
  color: {
    bg: '--gk-color-bg',
    surface: '--gk-color-surface',
    surfaceElevated: '--gk-color-surface-elevated',
    border: '--gk-color-border',
    borderStrong: '--gk-color-border-strong',
    text: '--gk-color-text',
    textMuted: '--gk-color-text-muted',
    textOnPrimary: '--gk-color-text-on-primary',
    textDisabled: '--gk-color-text-disabled',
    onSurface: '--gk-color-on-surface',
    onSurfaceMuted: '--gk-color-on-surface-muted',
    primary: '--gk-color-primary',
    primaryHover: '--gk-color-primary-hover',
    primaryActive: '--gk-color-primary-active',
    buttonDangerHover: '--gk-button-danger-hover',
    buttonDangerActive: '--gk-button-danger-active',
    focusRing: '--gk-color-focus-ring',
    danger: '--gk-color-danger',
    dangerSurface: '--gk-color-danger-surface',
    success: '--gk-color-success',
    successSurface: '--gk-color-success-surface',
    info: '--gk-color-info',
    infoSurface: '--gk-color-info-surface',
    warning: '--gk-color-warning',
    warningSurface: '--gk-color-warning-surface',
    alertAccentThickness: '--gk-alert-accent-thickness',
    overlay: '--gk-color-overlay',
  },
  opacity: {
    disabled: '--gk-opacity-disabled',
    overlay: '--gk-opacity-overlay',
  },
  overlay: {
    scrim: '--gk-overlay-scrim',
    zIndex: '--gk-overlay-z-index',
  },
  dialog: {
    zIndex: '--gk-dialog-z-index',
    maxWidth: '--gk-dialog-max-width',
    scrollMaxHeight: '--gk-dialog-scroll-max-height',
    scrollMaxViewport: '--gk-dialog-scroll-max-viewport',
    shadow: '--gk-dialog-shadow',
  },
  bottomSheet: {
    zIndex: '--gk-bottom-sheet-z-index',
    maxHeight: '--gk-bottom-sheet-max-height',
    shadow: '--gk-bottom-sheet-shadow',
  },
  menu: {
    zIndex: '--gk-menu-z-index',
    minWidth: '--gk-menu-min-width',
    maxHeight: '--gk-menu-max-height',
    shadow: '--gk-menu-shadow',
    scrim: '--gk-menu-scrim',
  },
  card: {
    radius: '--gk-card-radius',
    shadow: '--gk-card-shadow',
    shadowHover: '--gk-card-shadow-hover',
    borderWidth: '--gk-card-border-width',
    padding: '--gk-card-padding',
    paddingCompact: '--gk-card-padding-compact',
    mediaMinHeight: '--gk-card-media-min-height',
    actionsMinHeight: '--gk-card-actions-min-height',
    actionsGap: '--gk-card-actions-gap',
    loaderOverlay: '--gk-card-loader-overlay',
  },
  tooltip: {
    zIndex: '--gk-tooltip-z-index',
    maxWidth: '--gk-tooltip-max-width',
    paddingX: '--gk-tooltip-padding-x',
    paddingY: '--gk-tooltip-padding-y',
    shadow: '--gk-tooltip-shadow',
  },
  tabs: {
    height: '--gk-tabs-height',
    sliderSize: '--gk-tabs-slider-size',
    sliderColor: '--gk-tabs-slider-color',
    sliderRadius: '--gk-tabs-slider-radius',
    insetPadding: '--gk-tabs-inset-padding',
    insetRadius: '--gk-tabs-inset-radius',
    insetSelectedBg: '--gk-tabs-inset-selected-bg',
    fixedMaxWidth: '--gk-tabs-fixed-max-width',
    shiftScale: '--gk-tabs-shift-scale',
    shiftOpacity: '--gk-tabs-shift-opacity',
    bgColor: '--gk-tabs-bg-color',
    color: '--gk-tabs-color',
  },
  pagination: {
    gap: '--gk-pagination-gap',
    activeColor: '--gk-pagination-active-color',
  },
  density: {
    controlMinHeightSm: '--gk-control-min-height-sm',
    controlMinHeightMd: '--gk-control-min-height-md',
    controlMinHeightSlimSm: '--gk-control-min-height-slim-sm',
    controlMinHeightSlimMd: '--gk-control-min-height-slim-md',
    controlPaddingX: '--gk-control-padding-x',
    controlPaddingY: '--gk-control-padding-y',
    controlDisabledSurface: '--gk-control-disabled-surface',
  },
  focus: {
    offset: '--gk-focus-offset',
    width: '--gk-focus-width',
    ringWidth: '--gk-focus-ring-width',
    inputRingSpread: '--gk-input-focus-ring-spread',
  },
  radius: {
    sm: '--gk-radius-sm',
    md: '--gk-radius-md',
    lg: '--gk-radius-lg',
  },
  space: {
    1: '--gk-space-1',
    2: '--gk-space-2',
    3: '--gk-space-3',
    4: '--gk-space-4',
    5: '--gk-space-5',
    6: '--gk-space-6',
  },
  font: {
    sans: '--gk-font-sans',
    heading: '--gk-font-heading',
    sizeSm: '--gk-font-size-sm',
    sizeMd: '--gk-font-size-md',
    lineHeightTight: '--gk-line-height-tight',
    lineHeightNormal: '--gk-line-height-normal',
  },
  /** Step scales (25–900) for custom UI; semantic colors prefer `gkTokens.color.*` */
  palette: {
    baseWhite: '--gk-palette-base-white',
    baseBlack: '--gk-palette-base-black',
    gray: {
      '25': '--gk-palette-gray-25',
      '50': '--gk-palette-gray-50',
      '100': '--gk-palette-gray-100',
      '200': '--gk-palette-gray-200',
      '300': '--gk-palette-gray-300',
      '400': '--gk-palette-gray-400',
      '500': '--gk-palette-gray-500',
      '600': '--gk-palette-gray-600',
      '700': '--gk-palette-gray-700',
      '800': '--gk-palette-gray-800',
      '900': '--gk-palette-gray-900',
    },
    primary: {
      '25': '--gk-palette-primary-25',
      '50': '--gk-palette-primary-50',
      '100': '--gk-palette-primary-100',
      '200': '--gk-palette-primary-200',
      '300': '--gk-palette-primary-300',
      '400': '--gk-palette-primary-400',
      '500': '--gk-palette-primary-500',
      '600': '--gk-palette-primary-600',
      '700': '--gk-palette-primary-700',
      '800': '--gk-palette-primary-800',
      '900': '--gk-palette-primary-900',
    },
    success: {
      '25': '--gk-palette-success-25',
      '50': '--gk-palette-success-50',
      '100': '--gk-palette-success-100',
      '200': '--gk-palette-success-200',
      '300': '--gk-palette-success-300',
      '400': '--gk-palette-success-400',
      '500': '--gk-palette-success-500',
      '600': '--gk-palette-success-600',
      '700': '--gk-palette-success-700',
      '800': '--gk-palette-success-800',
      '900': '--gk-palette-success-900',
    },
    error: {
      '25': '--gk-palette-error-25',
      '50': '--gk-palette-error-50',
      '100': '--gk-palette-error-100',
      '200': '--gk-palette-error-200',
      '300': '--gk-palette-error-300',
      '400': '--gk-palette-error-400',
      '500': '--gk-palette-error-500',
      '600': '--gk-palette-error-600',
      '700': '--gk-palette-error-700',
      '800': '--gk-palette-error-800',
      '900': '--gk-palette-error-900',
    },
    warning: {
      '25': '--gk-palette-warning-25',
      '50': '--gk-palette-warning-50',
      '100': '--gk-palette-warning-100',
      '200': '--gk-palette-warning-200',
      '300': '--gk-palette-warning-300',
      '400': '--gk-palette-warning-400',
      '500': '--gk-palette-warning-500',
      '600': '--gk-palette-warning-600',
      '700': '--gk-palette-warning-700',
      '800': '--gk-palette-warning-800',
      '900': '--gk-palette-warning-900',
    },
    info: {
      '25': '--gk-palette-info-25',
      '50': '--gk-palette-info-50',
      '100': '--gk-palette-info-100',
      '200': '--gk-palette-info-200',
      '300': '--gk-palette-info-300',
      '400': '--gk-palette-info-400',
      '500': '--gk-palette-info-500',
      '600': '--gk-palette-info-600',
      '700': '--gk-palette-info-700',
      '800': '--gk-palette-info-800',
      '900': '--gk-palette-info-900',
    },
  },
  elevation: {
    1: '--gk-elevation-1',
    2: '--gk-elevation-2',
    3: '--gk-elevation-3',
    4: '--gk-elevation-4',
    5: '--gk-elevation-5',
  },
  /** Named text styles from the design system (size / weight / line-height variables) */
  text: {
    headingMSize: '--gk-text-heading-m-size',
    headingMWeight: '--gk-text-heading-m-weight',
    headingMLineHeight: '--gk-text-heading-m-line-height',
    headingMBoldWeight: '--gk-text-heading-m-bold-weight',
    headingSSize: '--gk-text-heading-s-size',
    headingSWeight: '--gk-text-heading-s-weight',
    headingSLineHeight: '--gk-text-heading-s-line-height',
    bodySSize: '--gk-text-body-s-size',
    bodySWeight: '--gk-text-body-s-weight',
    bodySLineHeight: '--gk-text-body-s-line-height',
    bodyXsSize: '--gk-text-body-xs-size',
    bodyXsWeight: '--gk-text-body-xs-weight',
    bodyXsLineHeight: '--gk-text-body-xs-line-height',
    buttonLSize: '--gk-text-button-l-size',
    buttonMSize: '--gk-text-button-m-size',
    buttonSSize: '--gk-text-button-s-size',
    chipSize: '--gk-text-chip-size',
    inputLabelSize: '--gk-text-input-label-size',
    placeholderSize: '--gk-text-placeholder-size',
    helperSize: '--gk-text-helper-size',
  },
  motion: {
    durationFast: '--gk-duration-fast',
    durationNormal: '--gk-duration-normal',
    easingStandard: '--gk-easing-standard',
  },
  snackbar: {
    zIndex: '--gk-snackbar-z-index',
    inset: '--gk-snackbar-inset',
    maxWidth: '--gk-snackbar-max-width',
    minHeight: '--gk-snackbar-min-height',
    shadow: '--gk-snackbar-shadow',
  },
  table: {
    border: '--gk-table-border',
    headerBg: '--gk-table-header-bg',
    headerText: '--gk-table-header-text',
    rowHover: '--gk-table-row-hover',
    stripe: '--gk-table-stripe',
    stickyShadowStart: '--gk-table-sticky-shadow-start',
    stickyShadowEnd: '--gk-table-sticky-shadow-end',
    cellPaddingY: '--gk-table-cell-padding-y',
    cellPaddingX: '--gk-table-cell-padding-x',
    densityComfortableMinHeight: '--gk-table-density-comfortable-min-height',
    densityCompactMinHeight: '--gk-table-density-compact-min-height',
    radius: '--gk-table-radius',
    loadingOpacity: '--gk-table-loading-opacity',
    sortIconSize: '--gk-table-sort-icon-size',
  },
} as const

export type GkTokenPath = keyof typeof gkTokens.color
