/**
 * Typed token names for CSS variables (use with getComputedStyle or documentation).
 */
export const gkTokens = {
  color: {
    bg: '--gk-color-bg',
    surface: '--gk-color-surface',
    surfaceElevated: '--gk-color-surface-elevated',
    border: '--gk-color-border',
    borderStrong: '--gk-color-border-strong',
    text: '--gk-color-text',
    textMuted: '--gk-color-text-muted',
    textOnPrimary: '--gk-color-text-on-primary',
    textDisabled: '--gk-color-text-disabled',
    onSurface: '--gk-color-on-surface',
    onSurfaceMuted: '--gk-color-on-surface-muted',
    primary: '--gk-color-primary',
    primaryHover: '--gk-color-primary-hover',
    primaryActive: '--gk-color-primary-active',
    buttonDangerHover: '--gk-button-danger-hover',
    buttonDangerActive: '--gk-button-danger-active',
    focusRing: '--gk-color-focus-ring',
    danger: '--gk-color-danger',
    dangerSurface: '--gk-color-danger-surface',
    success: '--gk-color-success',
    successSurface: '--gk-color-success-surface',
    info: '--gk-color-info',
    infoSurface: '--gk-color-info-surface',
    warning: '--gk-color-warning',
    warningSurface: '--gk-color-warning-surface',
    alertAccentThickness: '--gk-alert-accent-thickness',
    overlay: '--gk-color-overlay',
  },
  opacity: {
    disabled: '--gk-opacity-disabled',
    overlay: '--gk-opacity-overlay',
  },
  overlay: {
    scrim: '--gk-overlay-scrim',
    zIndex: '--gk-overlay-z-index',
  },
  dialog: {
    zIndex: '--gk-dialog-z-index',
    maxWidth: '--gk-dialog-max-width',
    scrollMaxHeight: '--gk-dialog-scroll-max-height',
    scrollMaxViewport: '--gk-dialog-scroll-max-viewport',
    shadow: '--gk-dialog-shadow',
  },
  bottomSheet: {
    zIndex: '--gk-bottom-sheet-z-index',
    maxHeight: '--gk-bottom-sheet-max-height',
    shadow: '--gk-bottom-sheet-shadow',
  },
  menu: {
    zIndex: '--gk-menu-z-index',
    minWidth: '--gk-menu-min-width',
    maxHeight: '--gk-menu-max-height',
    shadow: '--gk-menu-shadow',
    scrim: '--gk-menu-scrim',
  },
  tooltip: {
    zIndex: '--gk-tooltip-z-index',
    maxWidth: '--gk-tooltip-max-width',
    paddingX: '--gk-tooltip-padding-x',
    paddingY: '--gk-tooltip-padding-y',
    shadow: '--gk-tooltip-shadow',
  },
  tabs: {
    height: '--gk-tabs-height',
    sliderSize: '--gk-tabs-slider-size',
    sliderColor: '--gk-tabs-slider-color',
    sliderRadius: '--gk-tabs-slider-radius',
    insetPadding: '--gk-tabs-inset-padding',
    insetRadius: '--gk-tabs-inset-radius',
    insetSelectedBg: '--gk-tabs-inset-selected-bg',
    fixedMaxWidth: '--gk-tabs-fixed-max-width',
    shiftScale: '--gk-tabs-shift-scale',
    shiftOpacity: '--gk-tabs-shift-opacity',
    bgColor: '--gk-tabs-bg-color',
    color: '--gk-tabs-color',
  },
  pagination: {
    gap: '--gk-pagination-gap',
    activeColor: '--gk-pagination-active-color',
  },
  density: {
    controlMinHeightSm: '--gk-control-min-height-sm',
    controlMinHeightMd: '--gk-control-min-height-md',
    controlMinHeightSlimSm: '--gk-control-min-height-slim-sm',
    controlMinHeightSlimMd: '--gk-control-min-height-slim-md',
    controlPaddingX: '--gk-control-padding-x',
    controlPaddingY: '--gk-control-padding-y',
    controlDisabledSurface: '--gk-control-disabled-surface',
  },
  focus: {
    offset: '--gk-focus-offset',
    width: '--gk-focus-width',
    ringWidth: '--gk-focus-ring-width',
    inputRingSpread: '--gk-input-focus-ring-spread',
  },
  radius: {
    sm: '--gk-radius-sm',
    md: '--gk-radius-md',
    lg: '--gk-radius-lg',
  },
  space: {
    1: '--gk-space-1',
    2: '--gk-space-2',
    3: '--gk-space-3',
    4: '--gk-space-4',
    5: '--gk-space-5',
    6: '--gk-space-6',
  },
  font: {
    sans: '--gk-font-sans',
    sizeSm: '--gk-font-size-sm',
    sizeMd: '--gk-font-size-md',
  },
  motion: {
    durationFast: '--gk-duration-fast',
    durationNormal: '--gk-duration-normal',
    easingStandard: '--gk-easing-standard',
  },
  snackbar: {
    zIndex: '--gk-snackbar-z-index',
    inset: '--gk-snackbar-inset',
    maxWidth: '--gk-snackbar-max-width',
    minHeight: '--gk-snackbar-min-height',
    shadow: '--gk-snackbar-shadow',
  },
  table: {
    border: '--gk-table-border',
    headerBg: '--gk-table-header-bg',
    headerText: '--gk-table-header-text',
    rowHover: '--gk-table-row-hover',
    stripe: '--gk-table-stripe',
    stickyShadowStart: '--gk-table-sticky-shadow-start',
    stickyShadowEnd: '--gk-table-sticky-shadow-end',
    cellPaddingY: '--gk-table-cell-padding-y',
    cellPaddingX: '--gk-table-cell-padding-x',
    densityComfortableMinHeight: '--gk-table-density-comfortable-min-height',
    densityCompactMinHeight: '--gk-table-density-compact-min-height',
    radius: '--gk-table-radius',
    loadingOpacity: '--gk-table-loading-opacity',
    sortIconSize: '--gk-table-sort-icon-size',
  },
} as const

export type GkTokenPath = keyof typeof gkTokens.color
